//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiXTools.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RU_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RU_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiXTools.Properties.Languages.RU_Resources", typeof(RU_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу открыть приложение, потому что оно уже запущено в другом процессе!.
        /// </summary>
        internal static string APP_IS_ALREADY_RUNNING {
            get {
                return ResourceManager.GetString("APP_IS_ALREADY_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки приложения.
        /// </summary>
        internal static string APPLICATION_SETTINGS {
            get {
                return ResourceManager.GetString("APPLICATION_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL / файл для кнопки помощника.
        /// </summary>
        internal static string ASSISTANT_BUTTON_URL_OR_FILE {
            get {
                return ResourceManager.GetString("ASSISTANT_BUTTON_URL_OR_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно получить доступ к Mi Screen Saver, потому что он не существует или путь к Mi OSD Utility не настроен!.
        /// </summary>
        internal static string CANNOT_ACCESS_MI_SCREEN_SAVER {
            get {
                return ResourceManager.GetString("CANNOT_ACCESS_MI_SCREEN_SAVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменять.
        /// </summary>
        internal static string CHANGE {
            get {
                return ResourceManager.GetString("CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темный режим.
        /// </summary>
        internal static string DARK_MODE {
            get {
                return ResourceManager.GetString("DARK_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки разработчика.
        /// </summary>
        internal static string DEV_SETTINGS {
            get {
                return ResourceManager.GetString("DEV_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to английский.
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение папки.
        /// </summary>
        internal static string FOLDER_LOCATION {
            get {
                return ResourceManager.GetString("FOLDER_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to венгерский.
        /// </summary>
        internal static string HU {
            get {
                return ResourceManager.GetString("HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим запуска.
        /// </summary>
        internal static string LAUNCH_MODE {
            get {
                return ResourceManager.GetString("LAUNCH_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Консоль журнала.
        /// </summary>
        internal static string LOG_CONSOLE {
            get {
                return ResourceManager.GetString("LOG_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть консоль журнала при запуске.
        /// </summary>
        internal static string LOG_CONSOLE_ON_STARTUP {
            get {
                return ResourceManager.GetString("LOG_CONSOLE_ON_STARTUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiXTools.
        /// </summary>
        internal static string MIXTOOLS {
            get {
                return ResourceManager.GetString("MIXTOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to открыть.
        /// </summary>
        internal static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть консоль журнала.
        /// </summary>
        internal static string OPEN_LOG_CONSOLE {
            get {
                return ResourceManager.GetString("OPEN_LOG_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь для Mi OSD Utility не настроен!.
        /// </summary>
        internal static string OSD_PATH_IS_NOT_SET {
            get {
                return ResourceManager.GetString("OSD_PATH_IS_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi OSD Utility настройки.
        /// </summary>
        internal static string OSD_SETTINGS {
            get {
                return ResourceManager.GetString("OSD_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSDLauncher.exe не найден в выбранной папке!.
        /// </summary>
        internal static string OSDLAUNCHER_EXE_NOT_FOUND {
            get {
                return ResourceManager.GetString("OSDLAUNCHER_EXE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить данные приложения.
        /// </summary>
        internal static string RESET_APPDATA {
            get {
                return ResourceManager.GetString("RESET_APPDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to русский.
        /// </summary>
        internal static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to запустить от имени администратора.
        /// </summary>
        internal static string RUNAS {
            get {
                return ResourceManager.GetString("RUNAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хотели бы вы запускать выбранную программу от имени администратора при нажатии кнопки помощника?.
        /// </summary>
        internal static string SELECT_LAUNCH_MODE {
            get {
                return ResourceManager.GetString("SELECT_LAUNCH_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим запуска.
        /// </summary>
        internal static string SELECT_LAUNCH_MODE_TITLE {
            get {
                return ResourceManager.GetString("SELECT_LAUNCH_MODE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать заставку Mi.
        /// </summary>
        internal static string SHOW_MI_SCREEN_SAVER {
            get {
                return ResourceManager.GetString("SHOW_MI_SCREEN_SAVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложению не удалось загрузить исполняемый файл URLAndFilelauncher из репозитория GitHub. Пожалуйста, проверьте, есть ли у вас подключение к Интернету, чтобы загрузить необходимый файл и перезапустите приложение!.
        /// </summary>
        internal static string UAFL_DOWNLOAD_FAILED {
            get {
                return ResourceManager.GetString("UAFL_DOWNLOAD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uafl.exe отсутствует в каталоге приложения!.
        /// </summary>
        internal static string UAFL_FILE_IS_MISSING {
            get {
                return ResourceManager.GetString("UAFL_FILE_IS_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pежим УАФЛ.
        /// </summary>
        internal static string UAFL_MODE {
            get {
                return ResourceManager.GetString("UAFL_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только файлы .lnk и .exe можно запускать от имени администратора!.
        /// </summary>
        internal static string UAFL_MODE_CANNOT_BE_CHANGED {
            get {
                return ResourceManager.GetString("UAFL_MODE_CANNOT_BE_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение необходимо запускать от имени администратора!.
        /// </summary>
        internal static string UNAUTHORIZED_ACCEUNAUTHORIZED_ACCESS {
            get {
                return ResourceManager.GetString("UNAUTHORIZED_ACCEUNAUTHORIZED_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия.
        /// </summary>
        internal static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посетите GitHub.
        /// </summary>
        internal static string VISIT_GITHUB {
            get {
                return ResourceManager.GetString("VISIT_GITHUB", resourceCulture);
            }
        }
    }
}
